### ISSUE TITLE
[BUG] crontab: no crontab for user

### ISSUE THREAD

**Issue by lucianocn** [yii2tech/crontab#10] opened 2016-03-29 05:35 UTC
``` php
public function actionSetup()
{
    $cronTab = new CronTab();
    $cronTab->removeAll();

    $cronTab->setJobs([
        [
            'min' => '*',
            'hour' => '*',
            'command' => 'php ' . Yii::$app->basePath . '/yii crontab/setup',
        ],
    ]);
    $cronTab->apply();
}
```

---

Error:

``` php
Exception 'yii\base\Exception' with message 'Failure to setup crontab from file '/runtime/yii2tech_crontab_CronTabXZOr3B': "-":0: bad minute
crontab: errors in crontab file, can't install'

in /vendor/yii2tech/crontab/CronTab.php:186
```

---

Debug:

`crontab -l: crontab: no crontab for user`

**Comment by lucianocn** [comment] 2016-03-29 05:44
#9

**Comment by klimov-paul** [comment] 2016-03-29 12:41
What is a content of `/runtime/yii2tech_crontab_CronTabXZOr3B` file?

**Comment by klimov-paul** [comment] 2016-03-29 12:46
Unable to reproduce on CentOS.
What OS do you have?

**Comment by klimov-paul** [comment] 2016-03-29 13:06
Anyway I have improved the check to be more reliable.
Issue resolved by commit faa0966ed086c013b982a335a7912d79b31b9251

**Closed as completed by klimov-paul** 2016-03-29 13:06 UTC
Labels: bug

**Comment by lucianocn** [comment] 2016-03-29 15:19
@klimov-paul OS X El Capitan (10.11.4)

It's working now :thumbsup:

**Comment by aginanjar** [comment] 2016-04-18 19:48
@lucianocn how you fix this? I'm also get this bug too.

**Comment by klimov-paul** [comment] 2016-04-26 07:28
Upgrade up to 1.0.2
